spring:
  jpa:
    hibernate:
      ddl-auto: validate
#      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop
    username: demoshop
    password: pass
  flyway:
    baseline-on-migrate: true

